export enum AppRoutes {
    conditional='conditional',
    emotion = 'emotion',
    hooks = 'hooks',
    hooksSameParent='hooksSameParent',
    translations = 'translations',
    dates = 'dates',
    redux = 'redux',
    serverRequests = 'server-requests',
    formik = 'formik',
    forms = 'forms',
    lists='lists',
    props='props',
    stylesPage='stylesPage',
    tailWindCSS='tailwindCSS',
    times = 'times',    
    urql='urql',
    apolloclient='apolloClient',
    apolloclientTyped='apolloClientTyped',
    sass='sass' ,
    testPage='testPage',
    typescriptPage='typescriptPage'
}