name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - run: |
        npm i -g typescript@^4.9.5 
     - run: docker build . --file Dockerfile --tag tezine/reactapp:latest  
